### ISSUE TITLE
Makefile or similar?

### ISSUE THREAD

**Issue by jacmoe** [larso0/PTGame#1]
I am just wondering if you could add a makefile / project-file to the repository? :)

**Comment by larso0** [comment]
Hi. I added a makefile. Using this makefile, I can build the game on my arch linux installation (you need SDL2). Have another look at the readme for a small explanation of the project and in game controls.

**Comment by jacmoe** [comment]
Awesome!
The makefile 'maked' successfully on my Debian without a hitch.

Thanks a lot for taking the time to add this.
I am grateful because I have switched from C++ to C because I needed to go back to basics, and there isn't a lot of code in good old C using modern techniques.
